### ISSUE TITLE
ACM Certificate - Tags flapping

### ISSUE THREAD

**Issue by jlpedrosa** [crossplane-contrib/provider-aws#1930] opened 2023-10-24 11:08 UTC
### What happened?
Resource acm.Certificate is constantly reconciling, Tags are being set and removed.

goes from tags to without tags constantly:
```
 "spec": {
      
        "forProvider": {
          ...
            "region": "us-east-1",            
            "tags": [],
            "validationMethod": "EMAIL"
        },
        "providerConfigRef": {
            "name": "aws"
        }
    },

```

to:
```
 "forProvider": {
       ...
            "tags": [
                {
                    "key": "crossplane-kind",
                    "value": "certificate.acm.aws.crossplane.io"
                },
                {
                    "key": "crossplane-name",
                    "value": "private-ingress"
                },
                {
                    "key": "crossplane-providerconfig",
                    "value": "aws"
                }
            ],
            "validationMethod": "EMAIL"
        },     

```

### How can we reproduce it?
Creating a Private CA, and linking it to an object similar to:
```
 &acmv1alpha.Certificate{
		ObjectMeta: metav1.ObjectMeta{
			// TODO:
			Name: a.Component.GetName(),
		},
		Spec: acmv1alpha.CertificateSpec{
			ResourceSpec: xpv1.ResourceSpec{
				ProviderConfigReference: &xpv1.Reference{Name: awsEnv.Spec.XPProviderConfigName},
			},
			ForProvider: acmv1alpha.CertificateParameters{
				Region:                  awsEnv.Spec.Region,
				CertificateAuthorityARN: &CAArn,
				DomainName:              certificateCommonName,
				DomainValidationOptions: []*acmv1alpha.DomainValidationOption{
					{
						DomainName:       certificateCommonName,
						ValidationDomain: certificateCommonName,
					},
				},
				Options: &acmv1alpha.CertificateOptions{
					CertificateTransparencyLoggingPreference: "ENABLED",
				},
				SubjectAlternativeNames: []*string{&certificateCommonName},
				Tags:                    []acmv1alpha.Tag{
					//{Key: "cluster", Value: string(cluster.GetClusterID())},
					//{Key: "component", Value: "ingress-controller"},
					//{Key: "ingress", Value: a.Component.GetName()},
				},
				ValidationMethod: "EMAIL",
			},
		},
	}
```

### What environment did it happen in?
0.38, but there are not significant changes in ACM since then.

**Comment by MisterMX** [comment] 2023-10-25 12:49
Duplicate of #1498. See https://github.com/crossplane-contrib/provider-aws/issues/1498#issuecomment-1761412322 for an explanation of the current behaviour and how it could be solved.

**Comment by MisterMX** [comment] 2023-12-12 11:22
Fixed in #1938 by removing the standard tags all together.

**Closed by MisterMX** 2023-12-12 11:22 UTC
Labels: bug
