### ISSUE TITLE
provider-aws Install & build error, help me

### ISSUE THREAD

**Issue by Virusuki** [crossplane-contrib/provider-aws#1420] opened 2022-08-12 05:50 UTC
hi.
At https://github.com/crossplane-contrib/provider-aws/blob/master/INSTALL.md,
dir provider-aws, I git clone provider-aws and work with make -j4.

OS: ubuntu 20.04 env,,,
As you can see from the image, there is a build error. Please tell me the cause.

![provider-aws build issue](https://user-images.githubusercontent.com/70243256/184292370-194b8c21-cf92-4b7c-b888-8cda6c62377d.PNG)

**Comment by haarchri** [comment] 2022-08-12 07:26
Can you try first make submodules and mkdir .work ?

**Comment by Virusuki** [comment] 2022-08-12 08:09
I tried the make submodules command.
And the work directory was created.

I ran make -j4 again, but the error is the same. ㅠㅠ
Is there another way?

![이슈2](https://user-images.githubusercontent.com/70243256/184312676-d3ec1bfc-0767-4541-a156-b3ab68afe0ff.PNG)

**Comment by haarchri** [comment] 2022-08-12 08:48
Looks Like Go ist not installed / in path

**Comment by haarchri** [comment] 2022-10-02 11:52
did you checked your local env ? in your error message i can see that `go command not found` issue ?

**Comment by yuzhouliu9** [comment] 2023-01-09 16:20
The [INSTALL.md](https://github.com/crossplane-contrib/provider-aws/blob/master/INSTALL.md) instructions should be updated.
In a newly clone repo, following the instructions:
```
> make -j4
make: *** No rule to make target `do.build.images', needed by `xpkg.build.provider-aws'.  Stop.
```
This is caused by this [change](https://github.com/crossplane-contrib/provider-aws/commit/b1780e3992d0c19491ca9a60c70991f3616ff465). What is `do.build.images`? It doesn't exist anywhere in the repo.

Instead, you need to do `make submodules` first...
```
> make submodules
Submodule 'build' (https://github.com/upbound/build) registered for path 'build'
Cloning into '/Users/yuzhou.liu/code/provider-aws/build'...
Submodule path 'build': checked out '2d1bdbe92eb98b78a5bf78543f26b9a7fe9f7f1b'

> make -j4
11:14:27 [ .. ] verify go modules dependencies have expected content
11:14:27 [ .. ] installing up v0.13.0
11:14:29 [ OK ] installing up v0.13.0
all modules verified
11:14:30 [ OK ] go modules dependencies verified
...
```

Also `make help` does not exist even though it is mentioned in the installation instructions. It should be `make crossplane.help`.

**Comment by MisterMX** [comment] 2023-08-04 15:13
Closing this as the issue seems to be resolved.

**Closed by MisterMX** 2023-08-04 15:13 UTC
Labels: bug
