### ISSUE TITLE
New vpc/subnet tag feature from #1170 clobbers existing tags when adopting existing resources

### ISSUE THREAD

**Issue by jlee-idbydna** [crossplane-contrib/provider-aws#1236] opened 2022-03-29 23:04 UTC
### What happened?
In PR https://github.com/crossplane/provider-aws/pull/1170,
adoption of existing VPC or Subnets via external-name annotation will clobber existing tags.  This is especially problematic when adopting resources with `aws:` prefixed tags, such as EKSCTL created VPCs/Subnets.

I expect this behavior to be optional as stated in the PR.  Currently there does not appear to be a simple way to bypass this behavior.  

### How can we reproduce it?
Adopt any existing VPC or Subnet with pre-existing tags, via external-name annotation.

### What environment did it happen in?
Crossplane version: 1.7.0
provider-aws version: 0.25.0
EKS/Kubernetes: 1.21
OS: Amazon Linux 2

**Comment by haarchri** [comment] 2022-05-08 08:32
can you add the tags in the manifest definition before importing the resource ?

**Comment by jlee-idbydna** [comment] 2022-05-13 16:25
> can you add the tags in the manifest definition before importing the resource ?

That is a possible workaround, although somewhat unreasonable with dynamically generated tags for resources provisioned with tools such as `EKSCTL`.  It seems to me the fix is quite simple: to optionally allow a merge instead of an override strategy for tags.

**Comment by dlydiard** [comment] 2022-11-17 01:18
This is an issue if importing resources managed by another tool (such as Terraform). The auto-generated Terraform tags are clobbered by crossplane. Duplicating the tags is the manifest is also not a desired option as it forces to duplicate tags that were auto-generated from another tool. Crossplane should leave existing tags untouched and merge in the Crossplane related tags.

**Comment by dlydiard** [comment] 2023-08-28 16:51
We have a temporary workaround by denying crossplane access to create/delete VPC subnet tags.
```
        {
            "Effect": "Deny",
            "Action": [
                "ec2:DeleteTags",
                "ec2:CreateTags"
            ],
            "Resource": [
                "arn:aws:ec2:*:*:vpc/*",
                "arn:aws:ec2:*:*:subnet/*"
            ]
        }
```
The AWS provider seems to be working (importing the resource) even though it can't tag the resource.

**Comment by MisterMX** [comment] 2023-09-04 08:44
The general design idea in Crossplane is to have the managed resources as the single source of truth. Unless there are very specific technical reasons to merge external changes with MR settings, the controller should always overwrite settings in the external resource if they are different from the MR.

Preventing tag updates by denying access to the tagging API is not recommended since it leads to reconcile failures and will constantly trigger a rescheduling of that resource.

I am going to close this as this behaviour is by design. The best approach to this issue is to copy the auto-generated tags from the external resource and add them to the MR manually.

**Closed by MisterMX** 2023-09-04 08:44 UTC
Labels: bug
